flash_stache/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from flasharray.views import index

urlpatterns = [
    url(r'^flasharray/', include('flasharray.urls', namespace='flasharray', app_name='flasharray')),
    url(r'^$', index),
]

flasharray/urls.py
"""URL patterns."""

from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    url(r'^login/$', auth_views.login, name='login', kwargs={'template_name': 'flasharray/login.html'}),
    url(r'^logout/$', auth_views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'home.html', views.index, name='home'),
    url(r'logs.html', views.logs, name='logs'),
    url(r'^create_array', views.FlashArrayCreate.as_view(), name='create_array'),
    url(r'^delete_array/(?P<pk>[\w-]+)$', views.FlashArrayDelete.as_view(), name='delete_array'),
    url(r'^update_array/(?P<pk>[\w-]+)$', views.FlashArrayUpdate.as_view(), name='update_array'),
]

flasharray/models.py
"""Pure FlashArray API Monitoring Models."""

import datetime
import logging
import re
import os

from distutils.version import LooseVersion

import django_rq
import purestorage

from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse
from model_utils.models import TimeStampedModel
from multiselectfield import MultiSelectField

logger = logging.getLogger('flash_stache')

API_REQUESTS = {
    # Action will be used for database management
    # Save will append row(s)
    # Update will overwrite row(s)
    'array_alerts': {
        'action': 'save',
        'call': 'message?recent=true',
        'class': 'ArrayAlert',
    },
    'array_performance': {
        'action': 'save',
        'call': 'array?action=monitor',
        'class': 'ArrayPerformance',
    },
    'array_status': {
        'action': 'update',
        'call': 'array?controllers=true',
        'class': 'ArrayStatus',
    },
    'array_space': {
        'action': 'save',
        'call': 'array?space=true',
        'class': 'ArraySpace',
    },
    'host_connections': {
        'action': 'update',
        'call': 'host',
        'class': 'Host',
    },
    'host_details': {
        'action': 'update',
        'call': 'host?all=true',
        'class': 'HostDetails',
    },
    'host_performance': {
        'action': 'save',
        'call': 'host?action=monitor',
        'class': 'HostPerformance',
    },
    'host_space': {
        'action': 'save',
        'call': 'host?space=true',
        'class': 'HostSpace',
    },
    'hgroup_connections': {
        'action': 'update',
        'call': 'hgroup',
        'class': 'HostGroup',
    },
    'hgroup_performance': {
        'action': 'save',
        'call': 'hgroup?action=monitor',
        'class': 'HostGroupPerformance',
    },
    'hgroup_space': {
        'action': 'save',
        'call': 'hgroup?space=true',
        'class': 'HostGroupSpace',
    },
    'port_connections': {
        'action': 'update',
        'call': 'port?initiators=true',
        'class': 'Port',
    },
    #'purity_apps': {
    #    'action': 'update',
    #    'call': 'app',
    #    'class': 'PurityApp',
    #},
    'remote_assist': {
        'action': 'update',
        'call': 'array/remoteassist',
        'class': 'RemoteAssist',
    },
    'replication_peers': {
        'action': 'update',
        'call': 'array/connection',
        'class': 'ReplicationPeer',
    },
    'replication_transfers': {
        'action': 'update',
        # This one requires heavy post-processing as it returns all history of snapshot transfers.
        'call': 'pgroup?snap=true&transfer=true',
        'class': 'ReplicationTransfers',
    },
    'volume_performance': {
        'action': 'save',
        'call': 'volume?action=monitor',
        'class': 'VolumePerformance',
    },
    'volume_space': {
        'action': 'save',
        'call': 'volume?space=true&snap=true',
        'class': 'VolumeSpace'
    },
}


def _header(string):
    """Make API REQUEST strings human readable."""
    # Example: volume_space -> Volume Space
    camelized = []
    split = string.split('_')
    for word in split:
        word = word.lower()
        camel = word[0].upper() + word[1:]
        camelized.append(camel)
    return ' '.join(camelized)


TEMPLATES = os.listdir(os.path.join(os.path.dirname(__file__), 'grafana_templates'))
DASHES = [(template, _header(template)) for template in [item.split('.')[0] for item in TEMPLATES]]
INTERVALS = ((5, '5 seconds'),
             (30, '30 seconds'),
             (60, '60 seconds'))
NETWORK_SERVICES = (('iscsi', 'iscsi'),
                    ('management', 'management'),
                    ('replication', 'replication'))
RETENTIONS = ((24, '24 hours'), (48, '48 hours'), (72, '72 hours'))


class FlashArray(TimeStampedModel):
    """A Pure FlashArray form which will be used for validation/web-interface/database/etc."""
    alphanumeric = RegexValidator(r'\.|\,|\\|\/|\%|\*',
                                  'Hostname cannot contain SQL special characters such as: .,%\/*.',
                                  inverse_match=True)
    calls = tuple([(key, _header(key)) for key in sorted(API_REQUESTS.keys())])
    hostname = models.CharField(max_length=100, unique=True, help_text='A Unique Name',
                                validators=[alphanumeric], primary_key=True)
    ip_address = models.GenericIPAddressField(unique=True,
                                              help_text='The IP Address of vir0 is recommended')
    # REST API tokens are 36 characters long (including - delimiters).
    api_token = models.CharField(validators=[RegexValidator(regex=r'\w{8}-(\w{4}-){3}\w{12}',
                                 message='Invalid API Token', code='nomatch')],
                                 help_text='xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', max_length=36)
    interval = models.PositiveIntegerField('Interval', choices=INTERVALS, default=30)
    retention_hours = models.IntegerField('Database Retention', choices=RETENTIONS, default=24)
    default_dashes = [item[0].split('.')[0] for item in DASHES] or 'No dashboards found'
    dashboards = MultiSelectField(choices=DASHES, null=True, default=default_dashes)
    enabled = models.BooleanField('Enabled', default=True)
    # Read-only Fields
    date_added = models.DateTimeField(auto_now_add=True, editable=False)
    queue = models.CharField('queue', max_length=16, default='default', editable=False)
    db_job_id = models.CharField('db job id', max_length=128, editable=False, blank=True, null=True)
    job_id = models.CharField('job id', max_length=128, editable=False, blank=True, null=True)
    requests = MultiSelectField(choices=calls, default=[item[0] for item in calls], editable=False)

    def __str__(self):
        return self.hostname

    def clean(self):
        """Custom clean method to test a connection attempt to the API for validation."""
        super(FlashArray, self).clean()
        self.hostname = self.hostname.lower()
        try:
            connection = purestorage.FlashArray(self.ip_address, api_token=self.api_token)
            api_version = connection.get_rest_version()
            if LooseVersion(api_version) < LooseVersion('1.6'):
                message = 'Found API Version {} (1.6+ is required).  Consider upgrading Purity.'
                raise ValidationError(message.format(api_version))
        except purestorage.PureError:
            message = 'Failed to connect to {}.  Please verify IP Address and API Token.'
            raise ValidationError(message.format(self.ip_address))

    def delete(self, *args, **kwargs):
        # Unschedule running jobs.
        self.unschedule()
        # Clean-out entries in all related database tables.
        # TODO: This may need to be done manually, select_related isn't finding everything.
        # FlashArray.objects.filter(hostname=self.hostname).select_related().delete()
        super(FlashArray, self).delete(*args, **kwargs)

    def is_scheduled(self):
        """Check if a job is scheduled via job_id."""
        return self.job_id in self.fetch_scheduler()

    def save(self, **kwargs):
        """Save the FlashArray information to DB."""
        self.unschedule()
        if self.enabled:
            self.schedule()
        super(FlashArray, self).save(**kwargs)
        logger.info('Saved job {} for {}.'.format(self.job_id, self.hostname))

    def schedule(self):
        """Schedule a job/add it to the schedule DB."""
        if not self.enabled:
            return False
        scheduler = self.fetch_scheduler()
        # Check if there are jobs already running for this array; if so unschedule them.
        self.unschedule()
        kwargs = {'hostname': self.hostname,
                  'ip_address': self.ip_address,
                  'api_token': self.api_token,
                  'requests': self.requests}
        job = scheduler.schedule(func='flasharray.tasks.get_from_api',
                                 kwargs=kwargs,
                                 interval=self.interval,
                                 scheduled_time=datetime.datetime.utcnow(),
                                 repeat=None)  # Repeat indefinitely
        self.job_id = job.id
        logger.info('Scheduled API job: {} for {}.'.format(job.id, self.hostname))
        # Schedule a database clean-up job as well:
        db_job = scheduler.schedule(func='flasharray.tasks.clean_database',
                                    kwargs={'hostname': self.hostname,
                                            'requests': self.requests,
                                            'retention_hours': self.retention_hours},
                                    interval=86400,  # 24 hours in seconds
                                    scheduled_time=datetime.datetime.utcnow(),
                                    repeat=None)  # Repeat indefinitely
        logger.info('Scheduled clean-up job: {} for {}.'.format(db_job.id, self.hostname))
        self.db_job_id = db_job.id
        return True

    def fetch_scheduler(self):
        """Fetch the scheduler for the assigned queue."""
        return django_rq.get_scheduler(self.queue)

    def unschedule(self):
        """Unschedule a job via job_id."""
        if self.is_scheduled():
            self.fetch_scheduler().cancel(self.job_id)
            self.fetch_scheduler().cancel(self.db_job_id)
            logger.info('Cancelled job: {} for {}.'.format(self.job_id, self.hostname))
            logger.info('Cancelled job: {} for {}.'.format(self.db_job_id, self.hostname))
        self.job_id = None
        self.db_job_id = None
        return True

    def get_absolute_url(self):
        """Return to home after editing/deleting/etc."""
        return '/flasharray/home.html'

    class Meta:
        """Metadata for displaying/ordering information regarding FlashArray(s)."""

flasharray/forms.py
"""Forms."""

flasharray/views.py
"""Views/Pages."""

import logging
import socket

from django.contrib.auth.decorators import login_required
from django.forms import ModelForm
from django.shortcuts import render
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from flasharray import models
from flasharray import tasks

logger = logging.getLogger('flash_stache')


@login_required(login_url='flasharray/login')
def index(request):
    """Generate a list of FlashArray objects ordered by hostname for the base page."""
    # pylint: disable=no-member
    ip_addr = socket.gethostbyname(socket.gethostname())
    context = {
        'arrays': models.FlashArray.objects.distinct(),
        'remote_assist': models.RemoteAssist.objects.distinct(),
        'array_status': models.ArrayStatus.objects.distinct(),
        'url': 'http://{}'.format(ip_addr),
        'grafana': 'http://{}:3000'.format(ip_addr),
    }
    logger.info('Loaded Home Page.')
    return render(request, 'home.html', context)


def logs(request):
    """Fetch log_files for displaying most recent contents."""
    log_files = tasks.get_logs()
    context = {'logs': log_files}
    logger.info('Loaded Logs Page.')
    return render(request, 'logs.html', context=context)


class FlashArrayForm(ModelForm):
    """Base form for creating/modifying a FlashArray."""
    class Meta:
        model = models.FlashArray
        fields = ['hostname',
                  'ip_address',
                  'api_token',
                  'interval',
                  'retention_hours',
                  'enabled',
                  'dashboards']


class FlashArrayCreate(CreateView):
    """Simple view for Creating a FlashArray."""
    fields = '__all__'
    form = FlashArrayForm
    model = models.FlashArray
    template_name_suffix = '_create_form'
    success_url = '/flasharray/home.html'


class FlashArrayDelete(DeleteView):
    """Simple view for Deleting a FlashArray."""
    fields = '__all__'
    form = FlashArrayForm
    model = models.FlashArray
    template_name_suffix = '_delete_form'
    success_url = '/flasharray/home.html'


class FlashArrayUpdate(UpdateView):
    """Simple view for Updating a FlashArray."""
    fields = ['interval', 'retention_hours', 'enabled', 'dashboards']
    form = FlashArrayForm
    model = models.FlashArray
    template_name_suffix = '_update_form'
    success_url = '/flasharray/home.html'

flasharray/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    {% block head %}
    <head>
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <script src="{% static 'js/jquery-3.2.0.js' %}"></script>
        <script src="{% static 'js/bootstrap.js' %}"></script>
        <script>
            $(document).ready(function(){
                $('[data-toggle="tooltip"]').tooltip();
            });
        </script>
        <title>
            {% block title %}
            {% endblock title %}
        </title>
    </head>`
    {% endblock head %}
    {% block nav %}
  <div class="jumbotron">
    <h1>FlashStache</h1>
    <p>A Simple and Responsive FlashArray Monitoring System.</p>
  </div>
    <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="https://github.com/PureStorage-OpenConnect/FlashStache">FlashStache</a>
        </div>
        <div class="collapse navbar-collapse navbar-ex1-collapse pull-right">
          <ul class="nav navbar-nav">
              <!-- User Login/Logout -->
              {% if user.is_authenticated %}
              <li class="divider-vertical"></li>
              <li><a href="{% url 'flasharray:logout' %}">Sign Out</a></li>
              <li class="divider-vertical"></li>
              {% else %}
              <li class="dropdown">
                  <a class="dropdown-toggle" href="{% url 'flasharray:login' %}" data-toggle="dropdown">Log In <strong class="caret"></strong></a>
                  <div class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;" id="login_menu">
                      <form action="" method="post" accept-charset="UTF-8">
                          {% csrf_token %}
                          <input id="user_username" style="margin-bottom: 15px;" type="text" name="username" placeholder="Username" size="30" />
                          <input id="user_password" style="margin-bottom: 15px;" type="password" name="password" placeholder="Password" size="30" />
                          <input id="user_remember_me" style="float: left; margin-right: 10px;" type="checkbox" name="user[remember_me]" value="1" />
                          <label class="string optional" for="user_remember_me"> Remember me</label>
                          <input class="btn btn-primary" style="clear: left; width: 100%; height: 32px; font-size: 13px;" type="submit" name="commit" value="Sign In" />
              </form>
            </div>
          </li>
            {% endif %}
          <li class="divider-vertical"></li>
            <!-- Other Links -->
            <li><a href="/">Home</a></li>
            <li><a href="/flasharray/templates/logs.html">Logs</a></li>
          </ul>
        </div>
    </nav> <!-- End of Navigation Bar -->
    <br>
    {% endblock %}
    <body>
    <style>body {padding-top: 1em; padding-left: 1em}</style>
        {% block content %}

        {% endblock %}
    </body>
</html>

flasharray/templates/home.html
{% extends 'base.html' %}

{% block title %}
    FlashArray Home
{% endblock title %}
<body>
    {% block content %}
        <div class="container-fluid">
            <table class="table table-bordered" align="center">
                <thead>
                <tr>
                    <th>FlashArray Name</th>
                    <th>Remote Assist Status</th>
                    <th>Controller Status</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <h4><a href="/flasharray/create_array"><span class="glyphicon glyphicon-plus"></span> Add a FlashArray</a></h4>
                    </td>
                    <td><h4>-</h4></td>
                    <td><h4>-</h4></td>
                </tr>
                {% for array in arrays %}
                <tr>
                    <!-- Name -->
                    <td><h4> {{array.hostname}}</h4><a class="btn btn-warning btn-sm" href="/flasharray/update_array/{{array.hostname}}">
                        <span class="glyphicon glyphicon-wrench"></span> Edit</a>
                        <a class="btn btn-danger btn-sm" href="/flasharray/delete_array/{{array.hostname}}">
                        <span class="glyphicon glyphicon-trash"></span> Delete</a>
                        <a class="btn btn-info btn-sm" href={{grafana}}/dashboard/script/flash_stache.js?hostname={{array.hostname}}&{{array.dashboards|join:"&"}} target="_blank">Open Dashboard</a>
                        <a class="btn btn-success btn-sm" href="https://{{array.ip_address}}" target="_blank">Open GUI</a>
                    </td>
                    <!-- Remote Assist Status -->
                    <td>
                    {% if not remote_assist %}
                        <h4 style="color:white background-color:yellow!important">Unknown</h4>
                    {% else %}
                        {% for array_connection in remote_assist %}
                            {% if array_connection.hostname == array.hostname %}
                            {% if array_connection.status %}
                            <h4 style="color:white background-color:green!important">Connected</h4>
                            {% else %}
                            <h4 style="color:white background-color:red!important">Not Connected</h4>
                            {% endif %}
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                    </td>
                    <!-- Controller Status -->
                    <td>
                        {% if not array_status %}
                            <h4 style="color:white background-color:yellow!important">Unknown</h4>
                        {% else %}
                            {% for controller in array_status %}
                                {% if controller.hostname == array.hostname %}
                                <h4>{{controller.name}}: ({{controller.model}}/Purity {{controller.version}}) {{controller.mode}}: {{controller.status}}</h4>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    </td>
                </tr>
                </tbody>
                {% endfor %}
        </table> <!-- End Table -->
        </div> <!-- End Fluid Container -->
    {% endblock %}
</body>
</html>

flasharray/templates/logs.html
{% extends 'base.html' %}

{% block head %}
{{ block.super }}
<meta http-equiv="refresh" content="5" >
{% endblock head %}
{% block title %}
    Logs
{% endblock title %}


<!-- Main content -->
{% block content %}
    <div class="d-flex justify-content-between" style="monospace; font-family: 'Courier New'; font-size:12x">
        <br>
        {% for log_line in logs %}
            {{ log_line }}<br>
        {% endfor %}
    </div>
    <br>
{% endblock content %}

<!-- Optional scripts -->
<script>
{% block scripts %}
{% endblock scripts %}
</script>